export const frontendComponents = [
  {
    id: 'frontend',
    label: 'frontend',
    title: 'Frontend runtime overview',
    path: 'src/main.tsx -> src/app/App.tsx -> src/features/home/HomePage.tsx',
    what: 'This is the visible browser side of Xarticle.co.',
    how: 'The frontend boots in main.tsx, renders HomePage.tsx, stores request state in hooks, then hands the clean article to preview and export helpers.',
    why: 'It gives the user one place to paste a URL, watch the extraction happen, and use the final preview and downloads.',
    input: 'User clicks, URL text, and backend extraction responses.',
    output: 'A live preview and export actions in the browser.',
    dependsOn: 'React entrypoint, hooks, preview components, and export helpers.',
    usedBy: 'The browser runtime.',
  },
  {
    id: 'main-entry',
    label: 'main.tsx',
    title: 'Frontend entrypoint',
    path: 'src/main.tsx',
    what: 'Bootstraps the React app, mounts the root component, and swaps in the panda favicon.',
    how: 'It finds #root in the DOM, creates the React root, and renders App inside StrictMode.',
    why: 'Every frontend needs one first file that starts the app.',
    input: 'Browser DOM and imported App component.',
    output: 'A mounted Xarticle.co frontend.',
    dependsOn: 'App.tsx and the browser DOM.',
    usedBy: 'The browser directly loads it from index.html.',
  },
  {
    id: 'home-page',
    label: 'HomePage.tsx',
    title: 'Home page orchestrator',
    path: 'src/features/home/HomePage.tsx',
    what: 'Wires together the visible app sections, the extraction hook, the clipboard hook, and the export hook.',
    how: 'It creates the hooks once, then passes their state and handlers down into UrlSection, ExportSection, and PreviewSection.',
    why: 'This is the main frontend coordinator for the runtime page.',
    input: 'Hook state and handlers.',
    output: 'The visible single-page app layout.',
    dependsOn: 'useExtractionState, useClipboardPaste, useExportState, and home page components.',
    usedBy: 'App.tsx.',
  },
  {
    id: 'clipboard-paste',
    label: 'useClipboardPaste',
    title: 'Clipboard paste helper',
    path: 'src/features/home/hooks/useClipboardPaste.ts',
    what: 'Reads clipboard text into the URL field and reports paste notices or errors.',
    how: 'It tries to read clipboard text, places the result into the input state, and falls back to focus/error handling if the browser blocks clipboard access.',
    why: 'This makes the app faster to use when someone already copied an X link.',
    input: 'Clipboard text and error callbacks.',
    output: 'pasteFromClipboard(), notice text, and inputRef.',
    dependsOn: 'Browser clipboard APIs and HomePage state setters.',
    usedBy: 'HomePage.tsx and UrlSection.tsx.',
  },
  {
    id: 'extraction-state',
    label: 'useExtractionState',
    title: 'Extraction state controller',
    path: 'src/features/home/hooks/useExtractionState.ts',
    what: 'Owns the URL input, loading stage, current error, and current ExtractedArticle.',
    how: 'It stores local React state, classifies the URL, calls extractArticle.ts, and updates loading text like validating, fetching, and parsing.',
    why: 'Without this, the page would have no clear memory of where the request is in the pipeline.',
    input: 'User URL text and extraction results.',
    output: 'article, error, loading flags, and loadArticle().',
    dependsOn: 'xUrl.ts and extractArticle.ts.',
    usedBy: 'HomePage.tsx.',
  },
  {
    id: 'url-section-ui',
    label: 'UrlSection.tsx',
    title: 'URL input section',
    path: 'src/features/home/components/UrlSection.tsx',
    what: 'Renders the input box, paste button, load button, and validation notice for the URL.',
    how: 'It receives state and callbacks from HomePage.tsx and turns them into the visible input controls.',
    why: 'This is the user’s starting point in the runtime flow.',
    input: 'URL value, validation reason, and load/paste callbacks.',
    output: 'Visible URL input controls.',
    dependsOn: 'HomePage.tsx and browser form controls.',
    usedBy: 'HomePage.tsx.',
  },
  {
    id: 'export-state',
    label: 'useExportState',
    title: 'Export state controller',
    path: 'src/features/home/hooks/useExportState.ts',
    what: 'Owns PDF, print, and Markdown export state on the frontend.',
    how: 'It stores the current export mode, paper size, and margin preset, then calls pdfExport.ts or markdownExport.ts when the user clicks an export action.',
    why: 'The app needs one frontend controller that turns a ready article into download actions.',
    input: 'ExtractedArticle plus export settings from the UI.',
    output: 'downloadPdf(), printPdf(), downloadMarkdown(), and export state flags.',
    dependsOn: 'pdfExport.ts and markdownExport.ts.',
    usedBy: 'HomePage.tsx and ExportSection.tsx.',
  },
  {
    id: 'preview-section-ui',
    label: 'PreviewSection.tsx',
    title: 'Preview shell',
    path: 'src/features/home/components/PreviewSection.tsx',
    what: 'Chooses between loading skeleton, error box, empty state, or the real article preview.',
    how: 'It reads article/error/loading props and renders the right preview state for the current request.',
    why: 'The app needs a clean shell around the preview renderer itself.',
    input: 'article, error, and loading state.',
    output: 'Visible preview area.',
    dependsOn: 'ArticlePreview.tsx and HomePage state.',
    usedBy: 'HomePage.tsx.',
  },
  {
    id: 'export-section-ui',
    label: 'ExportSection.tsx',
    title: 'Export controls section',
    path: 'src/features/home/components/ExportSection.tsx',
    what: 'Renders the visible export buttons and option controls.',
    how: 'It receives export handlers and settings, then turns them into paper size, margin, PDF, print, and Markdown controls.',
    why: 'Users need a clear way to trigger downloads after the article is ready.',
    input: 'Export handlers, paper size, margin, and download state.',
    output: 'Visible export controls.',
    dependsOn: 'HomePage.tsx and useExportState.ts.',
    usedBy: 'HomePage.tsx.',
  },
  {
    id: 'x-url',
    label: 'xUrl.ts',
    title: 'URL normalizer and classifier',
    path: 'src/lib/xUrl.ts',
    what: 'Normalizes X URLs and decides whether a link is a status URL or an article URL.',
    how: 'It parses the URL, checks the host and pathname, then extracts IDs and a classification result.',
    why: 'The app needs to know which extraction path to use before it asks the worker for data.',
    input: 'Raw URL text.',
    output: 'Normalized URL plus status/article classification.',
    dependsOn: 'Browser URL parsing and helper functions inside xUrl.ts.',
    usedBy: 'useExtractionState.ts and extractArticle.ts.',
  },
  {
    id: 'extract-client',
    label: 'extractArticle.ts',
    title: 'Frontend extraction client',
    path: 'src/lib/extractArticle.ts',
    what: 'Sends the normalized URL to the worker and picks the right browser-side parser for the returned payload.',
    how: 'It validates the URL, POSTs to /api/extract, applies a timeout, then branches to threadloomParser.ts or articleParser.ts.',
    why: 'The frontend needs one clear orchestration file for backend requests and parser selection.',
    input: 'Normalized X URL and optional stage callback.',
    output: 'Promise of ExtractRequestResult with a clean ExtractedArticle.',
    dependsOn: '/api/extract, threadloomParser.ts, articleParser.ts.',
    usedBy: 'useExtractionState.ts.',
  },
]
