export const pipelineComponents = [
  {
    id: 'threadloom-parser',
    label: 'threadloomParser.ts',
    title: 'Status payload parser',
    path: 'src/lib/threadloomParser.ts',
    what: 'Turns the worker’s status payload into the final clean ExtractedArticle model.',
    how: 'It validates the payload, builds normalized blocks, maps metrics, and wraps everything into the shared domain model.',
    why: 'The worker returns a shaped status payload, but the browser still needs to finish adapting it into the one clean model the UI and exports use.',
    input: 'Status payload from /api/extract.',
    output: 'ExtractedArticle.',
    dependsOn: 'threadloom/blocks.ts, metrics.ts, normalize.ts, and domain types.',
    usedBy: 'extractArticle.ts.',
  },
  {
    id: 'html-parser',
    label: 'articleParser.ts',
    title: 'Browser HTML parser',
    path: 'src/lib/articleParser.ts',
    what: 'Turns raw article HTML into the final clean ExtractedArticle model.',
    how: 'It DOM-parses the HTML, extracts metadata, metrics, blocks, and warnings, and returns the shared clean article shape.',
    why: 'The article URL path brings back raw HTML, so the browser needs a parser for it.',
    input: 'Raw HTML plus the source URL.',
    output: 'ExtractedArticle.',
    dependsOn: 'article-parser/document.ts and parser helpers.',
    usedBy: 'extractArticle.ts.',
  },
  {
    id: 'document-parser',
    label: 'document.ts',
    title: 'DOM block extractor',
    path: 'src/lib/article-parser/document.ts',
    what: 'Walks the parsed article DOM and converts headings, paragraphs, quotes, code, lists, media, and embeds into ArticleBlock entries.',
    how: 'It scans the document tree, recognizes relevant tags, and normalizes them into the app’s block union.',
    why: 'The browser parser needs a lower-level specialist that understands how to turn HTML tags into clean content blocks.',
    input: 'Document object from parsed HTML.',
    output: 'Normalized blocks and inferred metadata.',
    dependsOn: 'DOM traversal and article parser helpers.',
    usedBy: 'src/lib/articleParser.ts.',
  },
  {
    id: 'article-model',
    label: 'ExtractedArticle',
    title: 'Shared clean article model',
    path: 'src/domain/article/extractedArticle.ts',
    what: 'Defines the single shared model the rest of the app trusts.',
    how: 'It stores the title, author, metrics, blocks, warnings, timestamps, provider info, and URLs in one consistent shape.',
    why: 'Preview, PDF, and Markdown should all read the same clean contract instead of each understanding raw source data.',
    input: 'Parser-produced fields.',
    output: 'Trusted runtime contract for the whole app.',
    dependsOn: 'Domain block and option types.',
    usedBy: 'Preview and export pipelines.',
  },
  {
    id: 'article-preview',
    label: 'ArticlePreview.tsx',
    title: 'Preview renderer',
    path: 'src/features/article-preview/ArticlePreview.tsx',
    what: 'Renders the normalized article on screen.',
    how: 'It composes the article header, metric grid, copy button, and block renderer into one preview card.',
    why: 'Users need to see the cleaned result before they download it.',
    input: 'ExtractedArticle.',
    output: 'Rendered preview JSX.',
    dependsOn: 'ArticleHeader, MetricGrid, ArticleBlocks, and text helpers.',
    usedBy: 'PreviewSection.tsx.',
  },
  {
    id: 'image-proxy',
    label: 'imageProxy.ts',
    title: 'Frontend image proxy bridge',
    path: 'src/lib/imageProxy.ts',
    what: 'Rewrites a remote X image URL into the worker image route.',
    how: 'It takes the original asset URL and returns /api/image?url=... so preview and PDF loading go through the worker proxy.',
    why: 'This is the little bridge between frontend asset rendering and the worker image route.',
    input: 'Remote image URL.',
    output: 'Worker image proxy URL.',
    dependsOn: '/api/image route.',
    usedBy: 'Preview rendering and pdfExport.ts.',
  },
  {
    id: 'pdf-export',
    label: 'pdfExport.ts',
    title: 'PDF export facade',
    path: 'src/lib/pdfExport.ts',
    what: 'Turns the clean article into a PDF download or print action.',
    how: 'It resolves images through the image proxy, builds a pdfmake document definition, then triggers download or print.',
    why: 'This is the human-friendly download and print path for reading outside the app.',
    input: 'ExtractedArticle and PDF options.',
    output: 'PDF download or print side effect.',
    dependsOn: 'pdf-export/definition.ts, pdfmake runtime, imageProxy.ts.',
    usedBy: 'useExportState.ts.',
  },
  {
    id: 'markdown-export',
    label: 'markdownExport.ts',
    title: 'Markdown export facade',
    path: 'src/lib/markdownExport.ts',
    what: 'Turns the clean article into Markdown or an offline ZIP with assets.',
    how: 'It decides whether plain Markdown is enough or whether media assets should be fetched and packed into a ZIP.',
    why: 'This is the LLM-friendly export path.',
    input: 'ExtractedArticle and download mode.',
    output: '.md or .zip download result.',
    dependsOn: 'markdown-export/build.ts, media.ts, packageZip.ts.',
    usedBy: 'useExportState.ts.',
  },
]
