export const workerComponents = [
  {
    id: 'worker-index',
    label: 'worker index',
    title: 'Worker router entrypoint',
    path: 'worker/src/index.ts',
    what: 'Routes incoming requests to /health, /api/image, or /api/extract.',
    how: 'It checks the request method and pathname, then calls the matching route handler.',
    why: 'The worker needs one front door that decides which handler should run.',
    input: 'Cloudflare Request.',
    output: 'Response from the right worker route.',
    dependsOn: 'handleExtract, handleImage, and jsonResponse.',
    usedBy: 'Cloudflare Worker runtime.',
  },
  {
    id: 'extract-route',
    label: 'extract route',
    title: 'Main extraction route',
    path: 'worker/src/routes/extract.ts',
    what: 'Handles POST /api/extract and chooses between the status/GraphQL path and the article/HTML path.',
    how: 'It parses the request body, validates the URL, checks cache, branches by URL type, and returns either status payload JSON or raw article HTML JSON.',
    why: 'This is the main backend controller for extraction.',
    input: 'POST body with url.',
    output: 'Status payload envelope, article HTML envelope, or error JSON.',
    dependsOn: 'url.ts, extractCache.ts, xClient.ts, xParsing.ts, tweetMapper.ts.',
    usedBy: 'worker/src/index.ts.',
  },
  {
    id: 'worker-url',
    label: 'worker url.ts',
    title: 'Worker URL parser',
    path: 'worker/src/core/url.ts',
    what: 'Parses backend input URLs and extracts status IDs or article IDs.',
    how: 'It uses URL parsing plus X-specific path patterns to tell which worker branch should run.',
    why: 'The worker cannot choose the right branch without first understanding the URL.',
    input: 'Incoming source URL.',
    output: 'Parsed URL, status ID, or article ID.',
    dependsOn: 'Worker URL helpers and patterns.',
    usedBy: 'routes/extract.ts.',
  },
  {
    id: 'worker-cache',
    label: 'extractCache.ts',
    title: 'Worker extract cache',
    path: 'worker/src/core/extractCache.ts',
    what: 'Reads and writes cached extract responses by source URL.',
    how: 'It builds a cache key from the URL, asks cacheStore.ts for a saved JSON record, and writes successful extraction envelopes back with a TTL.',
    why: 'This lets repeated requests skip expensive GraphQL or HTML fetch work when a cached response already exists.',
    input: 'Source URL, response status, and response payload.',
    output: 'Cached extract record or null.',
    dependsOn: 'cacheStore.ts and worker constants.',
    usedBy: 'routes/extract.ts.',
  },
  {
    id: 'x-client',
    label: 'xClient.ts',
    title: 'X GraphQL client',
    path: 'worker/src/core/xClient.ts',
    what: 'Talks to X/Twitter GraphQL for status extraction.',
    how: 'It discovers the current query ID and bearer token, activates a guest token, computes headers, and sends the GraphQL TweetResultByRestId request with a hedged multi-root strategy.',
    why: 'Status URLs need tweet data from X, and GraphQL is the worker path that gets it.',
    input: 'Status ID plus resolved auth/query values.',
    output: 'Raw GraphQL tweet payload.',
    dependsOn: 'xParsing.ts, durable state, state.ts, xHeaders.ts, http.ts.',
    usedBy: 'routes/extract.ts.',
  },
  {
    id: 'x-parsing',
    label: 'xParsing.ts',
    title: 'X payload and script parser',
    path: 'worker/src/core/xParsing.ts',
    what: 'Parses X script text and unwraps GraphQL tweet payloads.',
    how: 'It extracts things like main script URL, query ID, bearer token, transaction key, and the usable tweet node from the GraphQL result.',
    why: 'X data comes wrapped in a lot of extra structure, so the worker needs a specialist to peel it open.',
    input: 'Raw X HTML, raw JS text, and raw GraphQL JSON.',
    output: 'Worker-usable X internals and tweet nodes.',
    dependsOn: 'Regex and parsing helpers.',
    usedBy: 'xClient.ts and routes/extract.ts.',
  },
  {
    id: 'tweet-mapper',
    label: 'tweetMapper.ts',
    title: 'Worker tweet shaper',
    path: 'worker/src/core/tweetMapper.ts',
    what: 'Turns the raw tweet node into the worker payload contract.',
    how: 'It picks the useful author fields, metrics, URLs, timestamps, and embedded article data, then returns a smaller cleaner object.',
    why: 'The frontend should not have to understand X’s full raw tweet structure.',
    input: 'Unwrapped tweet node and requested status ID.',
    output: 'Worker tweet payload object.',
    dependsOn: 'worker articleParser.ts and primitive helpers.',
    usedBy: 'routes/extract.ts.',
  },
  {
    id: 'worker-article-parser',
    label: 'worker articleParser.ts',
    title: 'Worker embedded article parser',
    path: 'worker/src/core/articleParser.ts',
    what: 'Parses the article object that lives inside the tweet GraphQL data.',
    how: 'It reads content_state, entity maps, inline marks, markdown/code entities, and media entities, then shapes them into article blocks.',
    why: 'The status URL path carries article data inside tweet data, so the worker must pull it out and shape it.',
    input: 'Tweet node with embedded article fields.',
    output: 'Worker article payload with blocks, title, preview text, and cover media.',
    dependsOn: 'primitives.ts and tweet payload structure.',
    usedBy: 'tweetMapper.ts.',
  },
  {
    id: 'image-route',
    label: 'image route',
    title: 'Image proxy route',
    path: 'worker/src/routes/image.ts',
    what: 'Safely proxies allowed X image hosts through the worker.',
    how: 'It validates the target host, fetches the upstream asset with browser-like headers, and streams it back with safe CORS headers.',
    why: 'Preview and PDF image loading need a controlled asset path instead of hitting every remote host directly.',
    input: 'GET /api/image?url=...',
    output: 'Streamed image or video response.',
    dependsOn: 'Allowlisted hosts and fetch headers.',
    usedBy: 'imageProxy.ts and any preview/PDF image load.',
  },
]
